# -*- coding: utf-8 -*-
"""deeprmsca_env.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqFYmN2DoySxr5MejSbDVgb1cJx6ZgEU
"""

import gym
import numpy as np

from .rmsca_env import RMSCAEnv
from .optical_network_env import OpticalNetworkEnv


class DeepRMSCAEnv(RMSCAEnv):

    def __init__(self, topology=None, j=1,
                 episode_length=1000,
                 mean_service_holding_time=25.0,
                 mean_service_inter_arrival_time=1.,
                 num_spectrum_resources=100,
                 node_request_probabilities=None,
                 seed=None,
                 k_paths=5,
                 allow_rejection=False):
        super().__init__(topology=topology,
                         episode_length=episode_length,
                         load=mean_service_holding_time * mean_service_inter_arrival_time,
                         mean_service_holding_time=mean_service_holding_time,
                         num_spectrum_resources=num_spectrum_resources,
                         node_request_probabilities=node_request_probabilities,
                         seed=seed,
                         k_paths=k_paths,
                         allow_rejection=allow_rejection,
                         reset=False)

        self.j = j
        shape = 1 + 2 * self.topology.number_of_nodes() + (2 * self.j + 3) * self.k_paths * self.cores
        self.observation_space = gym.spaces.Box(low=0, high=1, dtype=np.uint8, shape=(shape,))
        self.action_space = gym.spaces.Discrete(self.k_paths  * self.cores * self.j + self.reject_action)
        self.action_space.seed(self.rand_seed)
        self.observation_space.seed(self.rand_seed)
        self.reset(only_counters=False)

    def step(self, action: int):
        if action < self.k_paths * self.j * self.cores:  # action is for assigning a path
            path, core, block = self._get_path_block_id(action)

            initial_indices, lengths = self.get_available_blocks(path, core)
            if block < len(initial_indices):
                return super().step([path, core, initial_indices[block]])
            else:
                return super().step([self.k_paths, self.cores, self.num_spectrum_resources])
        else:
            return super().step([self.k_paths, self.cores, self.num_spectrum_resources])

    def observation(self):
        # observation space defined as in https://github.com/xiaoliangchenUCD/DeepRMSCA/blob/eb2f2442acc25574e9efb4104ea245e9e05d9821/DeepRMSCA_Agent.py#L384
        source_destination_tau = np.zeros((2, self.topology.number_of_nodes()))
        min_node = min(self.service.source_id, self.service.destination_id)
        max_node = max(self.service.source_id, self.service.destination_id)
        source_destination_tau[0, min_node] = 1
        source_destination_tau[1, max_node] = 1
        spectrum_obs = np.full((self.k_paths * self.cores, 2 * self.j + 3), fill_value=-1.)
        for idp, path in enumerate(self.k_shortest_paths[self.service.source, self.service.destination]):
          for idc in range(self.cores):
            available_slots = self.get_available_slots(path, idc)
            num_slots = self.get_number_slots(path)
            initial_indices, lengths = self.get_available_blocks(idp, idc)

            for idb, (initial_index, length) in enumerate(zip(initial_indices, lengths)):
                        # initial slot index
                spectrum_obs[idp + (self.k_paths * idc), idb * 2 + 0] = 2 * (initial_index - .5 * self.num_spectrum_resources) / self.num_spectrum_resources

                        # number of contiguous FS available
                spectrum_obs[idp + (self.k_paths * idc), idb * 2 + 1] = (length - 8) / 8
            spectrum_obs[idp + (self.k_paths * idc), self.j * 2] = (num_slots - 5.5) / 3.5 # number of FSs necessary

            idx, values, lengths = DeepRMSCAEnv.rle(available_slots)

            av_indices = np.argwhere(values == 1) # getting indices which have value 1
            spectrum_obs[idp + (self.k_paths * idc), self.j * 2 + 1] = 2 * (np.sum(available_slots) - .5 * self.num_spectrum_resources) / self.num_spectrum_resources # total number available FSs
            spectrum_obs[idp + (self.k_paths * idc), self.j * 2 + 2] = (np.mean(lengths[av_indices]) - 4) / 4 # avg. number of FS blocks available
        bit_rate_obs = np.zeros((1, 1))
        bit_rate_obs[0, 0] = self.service.bit_rate / 100

        return np.concatenate((bit_rate_obs, source_destination_tau.reshape((1, np.prod(source_destination_tau.shape))),
                               spectrum_obs.reshape((1, np.prod(spectrum_obs.shape)))), axis=1)\
            .reshape(self.observation_space.shape)

    def reward(self):
        return 1 if self.service.accepted else -1

    def reset(self, only_counters=True):
        return super().reset(only_counters=only_counters)

    def _get_path_block_id(self, action: int) -> (int, int):
        path = action // (self.j * self.cores)
        core = action // (self.j * self.k_paths)
        block = action % self.j
        return path, core, block

